### ISSUE TITLE
Suggestion: python_requires=">= 3.6.9" in setup.py for use on Colab

### ISSUE THREAD

**Issue by camelia-c** [estripling/randtest#1]
Good evening,

I wanted to use your **randtest** package on Google Colab, which currently offers Python 3.6.9 , so I had to do the following workaround to get it installed:

```
cd /tmp   
git clone https://github.com/estripling/randtest   
cd /tmp/randtest   
sed -i 's/>= 3.7/>= 3.6.9/' setup.py   
make install  
```
After the installation succeeded, it worked ok.

It would be helpful to operate the change:

``` python_requires=">= 3.6.9" ```

 in setup.py of this repo , so that Colab users can install it directly via:

```pip install git+https://github.com/estripling/randtest```

Thank you!
Best regards,
Camelia

**Comment by estripling** [comment]
Hi Camelia,

Thank you for trying out `randtest`.  I updated the functionality accordingly. It should now work without the workaround.

Regards,
E. Stripling
